import Link from "next/link"
import { ArrowLeft, FileText } from "lucide-react"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#02040b] px-4 py-8 text-zinc-100 sm:px-6">
      <div className="mx-auto max-w-[760px] space-y-6">
        <Link href="/" className="inline-flex items-center gap-2 text-xs text-zinc-400 hover:text-zinc-100">
          <ArrowLeft className="h-3.5 w-3.5" />
          Back to home
        </Link>

        <div className="space-y-1">
          <p className="flex items-center gap-2 text-4xl font-semibold">
            <span className="grid h-8 w-8 place-items-center rounded-md bg-blue-500/15">
              <FileText className="h-4 w-4 text-blue-300" />
            </span>
            Terms Of Service
          </p>
          <p className="text-xs text-zinc-500">Last updated March 4, 2026</p>
        </div>

        <article className="prose prose-invert max-w-none text-zinc-200 prose-h3:text-zinc-100 prose-p:text-zinc-300 prose-li:text-zinc-300">
          <h3>1. Acceptance of Terms</h3>
          <p>
            By accessing or using WeaveDirector, you agree to be bound by these Terms of Service and all applicable laws and regulations.
            If you do not agree with any of these terms, you are prohibited from using our services.
          </p>

          <h3>2. Description of Service</h3>
          <p>
            WeaveDirector provides an AI-powered creative platform that assists users in generating marketing strategy, copy, visual concepts, and video storyboards.
            We reserve the right to modify, suspend, or discontinue the service at any time without notice.
          </p>

          <h3>3. User Accounts</h3>
          <p>
            To access certain features of the platform, you must register for an account.
            You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
            You must immediately notify us of any unauthorized use of your account.
          </p>

          <h3>4. Intellectual Property Rights</h3>
          <p>
            Your Content: You retain all rights to the original briefs and inputs you provide to the service.
            By using the service, you grant us a limited license to process this content solely for the purpose of generating your requested outputs.
          </p>
          <p>
            Generated Content: Subject to your compliance with these Terms, you own the outputs generated by the AI based on your inputs.
            However, due to the nature of machine learning, outputs may not be unique across users, and WeaveDirector does not guarantee complete originality of AI-generated content.
          </p>

          <h3>5. Acceptable Use</h3>
          <p>You agree not to use this service to:</p>
          <ul>
            <li>Generate content that is illegal, harmful, threatening, abusive, or harassing.</li>
            <li>Infringe upon the intellectual property rights of others.</li>
            <li>Attempt to bypass or breach any security mechanism of the platform.</li>
            <li>Use the platform for any automated scraping or data extraction without permission.</li>
          </ul>

          <h3>6. Limitation of Liability</h3>
          <p>
            In no event shall WeaveDirector or its suppliers be liable for any damages arising out of the use or inability to use the materials on WeaveDirector&apos;s website.
          </p>

          <h3>7. Contact Information</h3>
          <p>
            If you have any questions about these Terms, please contact us at <strong>legal@weavedirector.com</strong>.
          </p>
        </article>
      </div>
    </div>
  )
}

